---
- name: Install updates on RHEL in a verbose way
  hosts: all

  vars:
    debug: false

  tasks:

    - name: List packages ready to be updated
      ansible.builtin.yum:
        list: updates
      register: possible_updates

    - name: Display everything
      ansible.builtin.debug:
        msg: "{{ possible_updates }}"
      when:
        - debug

    - name: Display name and available version
      ansible.builtin.debug:
        msg: "{{ possible_updates | community.general.json_query('results[].[name, version]') | sort | unique }}"

    - name: Display package count
      ansible.builtin.debug:
        msg: "Found {{ possible_updates | community.general.json_query('results[].[name]') | sort | unique | length }} packages ready to be updated"

    - name: Check for RHEL minor release change (7.x)
      ansible.builtin.debug:
        msg: "RHEL release changes to {{ version }}"
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == '7'
        - (possible_updates | community.general.json_query('results[?name == `redhat-release-server`].version[]') | length) > 0
      vars:
        version: "{{ possible_updates | community.general.json_query('results[?name == `redhat-release-server`].version[]') | last }}"

    - name: Check for RHEL minor release change (8.x and later)
      ansible.builtin.debug:
        msg: "RHEL release changes to {{ version }}"
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version >= '8'
        - (possible_updates | community.general.json_query('results[?name == `redhat-release`].version[]') | length) > 0
      vars:
        version: "{{ possible_updates | community.general.json_query('results[?name == `redhat-release`].version[]') | last }}"

    - name: Check for CentOS minor release change (7.x)
      ansible.builtin.debug:
        msg: "CentOS release changes to {{ major }}.{{ minor }}"
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == '7'
        - (possible_updates | community.general.json_query('results[?name == `centos-release`].version[]') | length) > 0
      vars:
        major: "{{ possible_updates | community.general.json_query('results[?name == `centos-release`].version[]') | last }}"
        minor: "{{ possible_updates | community.general.json_query('results[?name == `centos-release`].release[]') | last }}"

    - name: Check for CentOS minor release change (8.x)
      ansible.builtin.debug:
        msg: "CentOS release changes to {{ version }}"
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == '8'
        - (possible_updates | community.general.json_query('results[?name == `centos-linux-release`].version[]') | length) > 0
      vars:
        version: "{{ possible_updates | community.general.json_query('results[?name == `centos-linux-release`].version[]') | last }}"

    - name: Check for CentOS Stream minor release change (8.x and later)
      ansible.builtin.debug:
        msg: "CentOS Stream release changes to {{ version }}"
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version >= '8'
        - (possible_updates | community.general.json_query('results[?name == `centos-stream-release`].version[]') | length) > 0
      vars:
        version: "{{ possible_updates | community.general.json_query('results[?name == `centos-stream-release`].version[]') | last }}"

    - name: Check for AlmaLinux minor release change (8.x and later)
      ansible.builtin.debug:
        msg: "AlmaLinux release changes to {{ version }}"
      when:
        - ansible_distribution == "AlmaLinux"
        - ansible_distribution_major_version >= '8'
        - (possible_updates | community.general.json_query('results[?name == `almalinux-release`].version[]') | length) > 0
      vars:
        version: "{{ possible_updates | community.general.json_query('results[?name == `almalinux-release`].version[]') | last }}"

    - name: Check for Rocky Linux minor release change (8.x and later)
      ansible.builtin.debug:
        msg: "Rocky Linux release changes to {{ version }}"
      when:
        - ansible_distribution == "Rocky"
        - ansible_distribution_major_version >= '8'
        - (possible_updates | community.general.json_query('results[?name == `rocky-release`].version[]') | length) > 0
      vars:
        version: "{{ possible_updates | community.general.json_query('results[?name == `rocky-release`].version[]') | last }}"

    - name: Update all packages
      ansible.builtin.yum:
        name: '*'
        state: latest
