---
- hosts: all
  tasks:

  - name: list packages ready to be updated
    yum:
      list: updates
    register: possible_updates
  
  - name: display name and available version
    debug: 
      msg: "{{ possible_updates | json_query('results[].[name, version]') }}"

  - name: display package count 
    debug: 
      msg: "Found {{ possible_updates.results | length }} packages ready to be updated"

  - name: check for Red Hat minor release change (7.x)
    debug:
      msg: "RHEL minor release will change to {{ possible_updates | json_query('results[?name == `redhat-release-server`].version[]')  | first }}"
    when: 
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == '7'
      - (possible_updates | json_query('results[?name == `redhat-release-server`].version[]') | length) > 0  

  - name: check for Red Hat minor release change (8.x)
    debug:
      msg: "RHEL minor release will change to {{ possible_updates | json_query('results[?name == `redhat-release`].version[]') | first }}"
    when: 
      - ansible_distribution == "RedHat" 
      - ansible_distribution_major_version == '8'
      - (possible_updates | json_query('results[?name == `redhat-release`].version[]') | length) > 0

  - name: check for CentOS minor release change
    debug:
      msg: "CentOS minor release will change to {{ possible_updates | json_query('results[?name == `centos-linux-release`].version[]') | first }}"
    when: 
      - ansible_distribution == "CentOS"
      - (possible_updates | json_query('results[?name == `centos-linux-release`].version[]') | length) > 0

  - name: install updates
    yum:
      name: '*'
      state: latest

